version: '3.3'

volumes:
  postgres_volume:

services:
  database:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: petcollaboration
      POSTGRES_USER: petcollaboration
      POSTGRES_DB: estore

